### ISSUE TITLE
Print a single line with How To

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/homebrew-hz#5]
When I install the `hz` command via `brew install hazelcast` then it should print at least a single line of help. Something like: "use hz help" to learn how to control Hazelcast. 

Otherwise it's not all that clear how to start. Right now it's not a massive concern as the user has to learn about our tap anyway. But once we are in the official brew repo then users will be able to find Hazelcast via "brew search" and at that point we have to tell them how to start.

**Comment by sparkingdark** [comment]
Is it open for work @jerrinot

**Comment by alparslanavci** [comment]
Fixed by #8
